In [1]:
import numpy as np

In [2]:
#one dimension array

list = [1,2,3,4,5]
array = np.array(list)

In [3]:
type(array)

numpy.ndarray

In [4]:
array.shape

(5,)

In [5]:
#two dimension array
list1 = [1,2,3,4,5]
list2 = [5,2,5,4,5]
list3 = [8,2,6,4,8]

arr1= np.array([list1,list2,list3])

In [6]:
arr1

array([[1, 2, 3, 4, 5],
       [5, 2, 5, 4, 5],
       [8, 2, 6, 4, 8]])

In [7]:
arr1.shape

(3, 5)

In [8]:
#indexing
array[2]

3

In [9]:
#change the element
array[2]=9

In [10]:
array

array([1, 2, 9, 4, 5])

In [11]:
array[1:]

array([2, 9, 4, 5])

In [12]:
array[::]

array([1, 2, 9, 4, 5])

In [13]:
#reversing the array
array[::-1]

array([5, 4, 9, 2, 1])

In [14]:
arr1

array([[1, 2, 3, 4, 5],
       [5, 2, 5, 4, 5],
       [8, 2, 6, 4, 8]])

In [15]:
arr1[:,2]

array([3, 5, 6])

In [16]:
arr1[1:,1:4]

array([[2, 5, 4],
       [2, 6, 4]])

In [17]:
arr1[:,3:]

array([[4, 5],
       [4, 5],
       [4, 8]])

In [18]:
arr1[:,3:].shape

(3, 2)

In [19]:
#EDA

In [20]:
array

array([1, 2, 9, 4, 5])

In [21]:
array>3

array([False, False,  True,  True,  True])

In [22]:
array[array>3]

array([9, 4, 5])

In [23]:
#reshape
arr1

array([[1, 2, 3, 4, 5],
       [5, 2, 5, 4, 5],
       [8, 2, 6, 4, 8]])

In [24]:
arr1.shape

(3, 5)

In [25]:
arr1.reshape(5,3)

array([[1, 2, 3],
       [4, 5, 5],
       [2, 5, 4],
       [5, 8, 2],
       [6, 4, 8]])

In [26]:
#create an array
np.arange(1,20,2)

array([ 1,  3,  5,  7,  9, 11, 13, 15, 17, 19])

In [27]:
np.arange(1,20,2).reshape(5,2)

array([[ 1,  3],
       [ 5,  7],
       [ 9, 11],
       [13, 15],
       [17, 19]])

In [28]:
array

array([1, 2, 9, 4, 5])

In [29]:
array*array

array([ 1,  4, 81, 16, 25])

In [30]:
arr1

array([[1, 2, 3, 4, 5],
       [5, 2, 5, 4, 5],
       [8, 2, 6, 4, 8]])

In [31]:
arr1*arr1

array([[ 1,  4,  9, 16, 25],
       [25,  4, 25, 16, 25],
       [64,  4, 36, 16, 64]])

In [32]:
np.ones((5,3))

array([[1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.]])

In [33]:
np.zeros((4,4))

array([[0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.]])

In [34]:
np.random.randint(20,56,6).reshape(2,3)

array([[37, 47, 51],
       [20, 40, 22]])